---
- name: Initialize OpenMediaVault development machine
  hosts: all
  become: true

  tasks:
    # During initialization of the Salt environment, OMV overwrites the sshd config
    # with its own default config. We have to avoid this as it's breaking the
    # vagrant ssh connection otherwise. This throws an error during installation
    # of the OpenMediaVault package, but it continues anyway as far as I see.
    # See the following file for the exact code we work around here:
    # https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/srv/salt/omv/deploy/ssh/20sshd_config.sls
    - name: Make sshd config file immutable
      ansible.builtin.file:
        path: /etc/ssh/sshd_config
        attributes: +i

    # During initialization of the Salt environment, OMV cleans all  ~/.ssh directories
    # to have a known environment for the beginning. We have to avoid this for the
    # default vagrant user's authorized_keys file as it's breaking the vagrant ssh
    # connection otherwise. This doesn't throw an error during installation
    # of OpenMediaVault somehow.
    # See the following file for the exact code we work around here:
    # https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/srv/salt/omv/deploy/ssh/10authorized_keys.sls
    - name: Make authorized_keys file immutable
      ansible.builtin.file:
        path: /home/vagrant/.ssh/authorized_keys
        attributes: +i

    - name: Install requirements for using ansible.builtin.apt_key
      ansible.builtin.apt:
        update_cache: yes
        install_recommends: no
        pkg:
          - gnupg

    - name: Install OpenMediaVault archive key
      ansible.builtin.apt_key:
        url: https://packages.openmediavault.org/public/archive.key
        keyring: /usr/share/keyrings/openmediavault-archive-keyring.gpg

    - name: Add OpenMediaVault repository to apt sources
      ansible.builtin.template:
        src: /vagrant/provisioning/apt/sources.list.d/openmediavault.list.j2
        dest: /etc/apt/sources.list.d/openmediavault.list
        owner: root
        group: root
        mode: '0644'

    - name: Install OpenMediaVault
      ansible.builtin.apt:
        update_cache: yes
        install_recommends: no
        pkg:
          - openmediavault

    - name: Initialize OpenMediaVault database
      ansible.builtin.command: /usr/sbin/omv-confdbadm populate

    - name: Deploy OpenMediaVault network configuration
      ansible.builtin.command: /usr/sbin/omv-salt deploy run systemd-networkd

    - name: Install vim
      ansible.builtin.apt:
        install_recommends: no
        pkg:
          - vim

    - name: Install git
      ansible.builtin.apt:
        install_recommends: no
        pkg:
          - git
          - git-flow

    - name: Install necessary PHP modules for development not being installed by OpenMediaVault itself
      ansible.builtin.apt:
        install_recommends: no
        pkg:
          - composer
          - php8.2-libvirt-php
          - php-xdebug
          - php-libvirt-php

    - name: Pin QEMU packages to backports repository
      ansible.builtin.template:
        src: /vagrant/provisioning/apt/preferences.d/99qemu-from-backports.j2
        dest: /etc/apt/preferences.d/99qemu-from-backports
        owner: root
        group: root
        mode: '0644'
      when: use_backports_for_qemu

    - name: Install QEMU
      ansible.builtin.apt:
        install_recommends: no
        pkg:
          - qemu-system
          - qemu-system-modules-spice

    - name: Install UEFI firmware for all platforms
      ansible.builtin.apt:
        install_recommends: no
        pkg:
          - ovmf
          - ovmf-ia32
          - qemu-efi-aarch64
          - qemu-efi-arm

    - name: Install libvirt
      ansible.builtin.apt:
        install_recommends: no
        pkg:
          - libvirt-daemon-driver-qemu